blueprint:
  name: Leak Notifier Sonos
  description: Send a notification to Sonos when any configured moisture sensor becomes moist
  domain: automation
  input:
    notify_device:
      name: Notify device
      description: "The device where the notification should be sent to."
      selector:
        device:
          integration: mobile_app

trigger:
  - event_data: {}
    event_type: state_changed
    platform: event

condition:
  - condition: template
    value_template: '{{ trigger.event.data.new_state.attributes.device_class == "moisture" }}'
  - condition: template
    value_template: '{{ trigger.event.data.new_state.state == "on" }}'

action:
  - service: tts.google_translate_say
    data:
      entity_id:
        - media_player.garage
        - media_player.kitchen
        - media_player.mudroom
        - media_player.master_bedroom
        - media_player.office
        - media_player.patio
      message: "{{ trigger.event.data.new_state.attributes.friendly_name }} has detected a leak. {{ trigger.event.data.new_state.attributes.friendly_name }} has detected a leak."

mode: single
